APP_NAME = "黑马坦克大战"

DEFAULT_FPS = 60
DEFAULT_DELAY = 1.0/DEFAULT_FPS # 0.016666666666666666

PADDING = 10
BLOCK = 60
MAP_WIDTH = BLOCK*13
MAP_HEIGHT = BLOCK*13
MAP_SIZE = (MAP_WIDTH,MAP_HEIGHT)
MAP_POS = (PADDING,PADDING)

INFO_WIDTH = BLOCK*5
INFO_HEIGHT = MAP_HEIGHT
INFO_SIZE = (INFO_WIDTH,INFO_HEIGHT)
INFO_POS = (MAP_WIDTH+2*PADDING,PADDING)

WINDOW_WIDTH = MAP_HEIGHT+INFO_WIDTH+3*PADDING
WINDOW_HEIGHT = MAP_HEIGHT+2*PADDING
WINDOW_SIZE = (WINDOW_WIDTH,WINDOW_HEIGHT)

SCALE = 0.8
REAL_WIDTH = int(WINDOW_WIDTH*SCALE)
REAL_HEIGHT = int(WINDOW_HEIGHT*SCALE)
REAL_SIZE = (REAL_WIDTH,REAL_HEIGHT)